module.exports = {

  //AUTH
  AUTH_FIELD_CHANGE: 'AUTH_FIELD_CHANGE',

  TOKEN_LOGIN: 'TOKEN_LOGIN',
  TOKEN_LOGIN_SUCCESS: 'TOKEN_LOGIN_SUCCESS',
  TOKEN_LOGIN_FAILURE: 'TOKEN_LOGIN_FAILURE',
  TOKEN_LOGIN_NO_KEY: 'TOKEN_LOGIN_NO_KEY',

  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_INVALID: 'REGISTER_INVALID',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

};
